#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(git rev-parse --show-toplevel)"
cd "$ROOT_DIR"

ALLOWED_REGEX='^(docs/harness/|\.github/codex-prompts/)'
DEFAULT_BRANCH="${DEFAULT_BRANCH:-${GITHUB_BASE_REF:-main}}"

status="BATCHING_IN_PROGRESS"
batch_id="UNKNOWN_BATCH"
next_batch="UNKNOWN"
remaining="unknown"
functions_total="unknown"
files_documented_total="unknown"

if [[ -f docs/harness/PROGRESS_STATE.md ]]; then
  if grep -Eq 'ALL BATCHES COMPLETE|Remaining batches: \*\*0\*\*|Next batch ID: \*\*None\*\*' docs/harness/PROGRESS_STATE.md; then
    status="BATCHING_COMPLETE"
  fi

  extracted_batch="$(sed -n 's/^- Batch ID: `\(BATCH_[0-9][0-9][0-9]\)`.*/\1/p' docs/harness/PROGRESS_STATE.md | head -n1 || true)"
  [[ -n "$extracted_batch" ]] && batch_id="$extracted_batch"

  extracted_next="$(sed -n 's/^- Next batch ID: \*\*\([^*][^*]*\)\*\*.*/\1/p' docs/harness/PROGRESS_STATE.md | head -n1 || true)"
  [[ -n "$extracted_next" ]] && next_batch="$extracted_next"

  extracted_remaining="$(sed -n 's/^- Remaining batches: \*\*\([0-9][0-9]*\)\*\*.*/\1/p' docs/harness/PROGRESS_STATE.md | head -n1 || true)"
  [[ -n "$extracted_remaining" ]] && remaining="$extracted_remaining"

  extracted_funcs="$(sed -n 's/^- Total functions\/methods documented (running, best-effort): \*\*\([0-9][0-9]*\)\*\*.*/\1/p' docs/harness/PROGRESS_STATE.md | head -n1 || true)"
  [[ -n "$extracted_funcs" ]] && functions_total="$extracted_funcs"

  extracted_files="$(sed -n 's/^- Total files documented (running): \*\*\([0-9][0-9]*\)\*\*.*/\1/p' docs/harness/PROGRESS_STATE.md | head -n1 || true)"
  [[ -n "$extracted_files" ]] && files_documented_total="$extracted_files"
fi

mapfile -t changed_files < <(git status --porcelain | awk '{print $2}')

if (( ${#changed_files[@]} == 0 )); then
  {
    echo "has_changes=false"
    echo "status=$status"
    echo "batch_id=$batch_id"
    echo "next_batch=$next_batch"
    echo "remaining_batches=$remaining"
    echo "files_documented_total=$files_documented_total"
    echo "functions_total=$functions_total"
  } >> "$GITHUB_OUTPUT"
  echo "No changes detected. Nothing to commit."
  exit 0
fi

invalid_files=()
for file in "${changed_files[@]}"; do
  if [[ ! "$file" =~ $ALLOWED_REGEX ]]; then
    invalid_files+=("$file")
  fi
done

if (( ${#invalid_files[@]} > 0 )); then
  echo "Disallowed file changes detected:" >&2
  printf ' - %s\n' "${invalid_files[@]}" >&2
  exit 1
fi

timestamp="$(date -u +%Y%m%d%H%M%S)"
branch_name="codex/harness-batch-${batch_id}-${timestamp}"

if [[ "$batch_id" == "UNKNOWN_BATCH" ]]; then
  commit_message="docs(harness): update harness docs"
  pr_title="docs(harness): update harness docs"
else
  commit_message="docs(harness): process ${batch_id}"
  pr_title="docs(harness): process ${batch_id}"
fi

# Build best-effort summaries from progress state.
processed_files_summary="Not available"
if [[ -f docs/harness/PROGRESS_STATE.md ]]; then
  processed_files_summary="$(awk '
    /^## Batch processed this run/ {in_section=1; next}
    /^## / && in_section {in_section=0}
    in_section && /^  - `/ {gsub(/^  - `|`$/, ""); print "- " $0}
  ' docs/harness/PROGRESS_STATE.md | head -n 20)"
  [[ -z "$processed_files_summary" ]] && processed_files_summary="Not available"
fi

pr_body=$(cat <<PRBODY
## Harness batch automation result

- Batch processed: \
  - ${batch_id}
- Files documented this run (best effort):
${processed_files_summary}
- Functions/methods documented total (best effort): ${functions_total}
- Remaining batches (best effort): ${remaining}
- Next batch ID (best effort): ${next_batch}
- Harness status: ${status}

> This PR was generated by the harness automation loop and is constrained to docs-only harness updates.
PRBODY
)

git checkout -b "$branch_name"
git add docs/harness .github/codex-prompts
if git diff --cached --quiet; then
  echo "No staged harness doc changes after filtering; skipping commit."
  {
    echo "has_changes=false"
    echo "status=$status"
    echo "batch_id=$batch_id"
    echo "next_batch=$next_batch"
    echo "remaining_batches=$remaining"
    echo "files_documented_total=$files_documented_total"
    echo "functions_total=$functions_total"
  } >> "$GITHUB_OUTPUT"
  exit 0
fi

git commit -m "$commit_message"

{
  echo "has_changes=true"
  echo "status=$status"
  echo "batch_id=$batch_id"
  echo "next_batch=$next_batch"
  echo "remaining_batches=$remaining"
  echo "files_documented_total=$files_documented_total"
  echo "functions_total=$functions_total"
  echo "branch_name=$branch_name"
  echo "commit_message=$commit_message"
  echo "pr_title=$pr_title"
  echo "pr_body<<EOF"
  echo "$pr_body"
  echo "EOF"
} >> "$GITHUB_OUTPUT"

echo "Prepared commit on ${branch_name}: ${commit_message}"
